language: generic
before_install:
  - wget http://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
  - tar xf arduino-cli_latest_Linux_64bit.tar.gz
  - mkdir -p $HOME/bin
  - mv arduino-cli $HOME/bin/arduino-cli
  - export PATH=$PATH:$HOME/bin
  - arduino-cli core update-index
  - arduino-cli config init --additional-urls https://downloads.arduino.cc/packages/package_staging_index.json
  - arduino-cli config dump
  - arduino-cli core update-index
  - arduino-cli core install arduino:megaavr
  - arduino-cli lib install Servo
#  - sed -i '/recipe.output.tmp_file={build.project_name}.hex/d' "$HOME/.arduino15/packages/STM32/hardware/stm32/1.8.0/platform.txt"
#  - sed -i '/recipe.output.save_file={build.project_name}.{build.variant}.hex/d' "$HOME/.arduino15/packages/STM32/hardware/stm32/1.8.0/platform.txt"
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/.
  - travis encrypt 9facd779f3c71f91ae7e870487ae91a200642fd5

addons:
  sonarcloud:
    organization: "thaironeloureiro"
    token:
      secure: "travis encrypt 9facd779f3c71f91ae7e870487ae91a200642fd5" # encrypted value of your token

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - '$HOME/.sonar/cache'
script:
    - |      
        arduino-cli cache clean
        build-wrapper-linux-x86-64 --out-dir sonarcloud/bo bash sonarcloud/build.sh
        sonar-scanner -Dproject.settings=sonar-project.properties -Dsonar.cfamily.cache.path=$HOME/.sonar/cache     
